// @license@ 
package nanosome.flow {
	
	/**
	 * Version of the nanosome-flow project.
	 * 
	 * <p>This version is automatically generated by the build process.</p>
	 */
	public const version: String = "@version@";
}
